Adding Drupal and devops
AlaaAttya/slacky-devs pull request #4
Opened 2018-01-08 17:06 UTC by iAhmadZain

### Slack channel name
- Drupal
- Amazeeio
- Wodby 
- Traefik 

### Category
- Dev
- DevOps
### Link

2018-01-08 23:09 UTC, AlaaAttya requested changes

2018-01-08 23:09 UTC, AlaaAttya commented on README.md
> +- [Drupal](https://drupal.slack.com)
@iAhmadZain plz add the link where the users can request getting an invitation for this community

2018-01-11 10:15 UTC, iAhmadZain commented
@AlaaAttya  done could you check please ?

2018-01-11 10:55 UTC, AlaaAttyaMohamed commented
@iAhmadZain good add the invitation links for these communities too

[amazeeio.io](https://amazeeio.slack.com)
[Wodby](https://wodby-community.slack.com)
[Traefik](https://traefik.slack.com)

2018-01-11 10:56 UTC, AlaaAttya commented
@iAhmadZain good add the invitation links for these communities too

amazeeio.io
Wodby
Traefik

2018-01-13 09:38 UTC, iAhmadZain commented
@AlaaAttya  Done ;)

2018-01-13 14:42 UTC, merged

2018-01-13 14:43 UTC, AlaaAttya commented
done, thanks @iAhmadZain 💯 👍